# Generated by Django 2.1.3 on 2018-11-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='controller',
            new_name='hard',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='robot',
            new_name='soft',
        ),
    ]
